[build-system]
requires = ['hatch-vcs>=0.3.0', 'hatchling>=1.24.2,<1.25']
build-backend = 'hatchling.build'

[project]
name = 'cogmodels'
dynamic = ['version']
description = ''
readme = 'README.md'
requires-python = '>=3.10'
license = 'MIT'
keywords = []
authors = [{ name = 'Chenhui Zhang', email = 'zhang.chenhui@outlook.com' }]
classifiers = [
  'Development Status :: 4 - Beta',
  'Programming Language :: Python :: 3.10',
  'Programming Language :: Python :: 3.11',
  'Programming Language :: Python :: 3.12',
  'Programming Language :: Python :: Implementation :: CPython',
  'Programming Language :: Python :: Implementation :: PyPy',
  'Programming Language :: Python',
]
dependencies = [
    "accelerate>=1.3.0",
    "datasets>=3.2.0",
    "decord>=0.6.0",
    "deepspeed>=0.16.3",
    "diffusers @ git+https://github.com/zRzRzRzRzRzRzR/diffusers@cogview4_control",
    "imageio>=2.37.0",
    "imageio-ffmpeg>=0.6.0",
    "opencv-python>=4.11.0.86",
    "peft>=0.14.0",
    "pydantic>=2.10.6",
    "sentencepiece>=0.2.0",
    "setuptools>=75.8.0",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
    "transformers>=4.48.3",
    'typer',
    "wandb>=0.19.6",
]


[project.urls]
# TODO: adds project urls
# Documentation = 'https://github.com/Chenhui Zhang/cogmodels#readme'
# Issues = 'https://github.com/Chenhui Zhang/cogmodels/issues'
# Source = 'https://github.com/Chenhui Zhang/cogmodels'


[tool.hatch.version]
source = 'vcs'


[tool.hatch.version.raw-options]
version_scheme = 'python-simplified-semver'
local_scheme = 'no-local-version'


[tool.hatch.build.hooks.vcs]
version-file = 'src/cogmodels/_version.py'


[tool.hatch.metadata]
allow-direct-references = true


[tool.ruff]
exclude = ['.git', '.mypy_cache', '.ruff_cache', '.venv', 'dist']
target-version = 'py310'
line-length = 100

[tool.ruff.format]
line-ending = 'lf'
quote-style = 'preserve'

[tool.ruff.lint]
select = ["E", "W"]
ignore = [
    "E999",
    "EXE001",
    "UP009",
    "F401",
    "TID252",
    "F403",
    "F841",
    "E501",
    "W293",
]

[tool.uv.sources]
diffusers = { git = "https://github.com/huggingface/diffusers" }


# TODO: test coverage
# [tool.coverage.run]
# source_pkgs = ['cogmodels', 'tests']
# branch = true
# parallel = true
# omit = ['src/cogmodels/__about__.py']

# [tool.coverage.paths]
# cogmodels = ['*/cogmodels/src/cogmodels', 'src/cogmodels']
# tests = ['*/cogmodels/tests', 'tests']

# [tool.coverage.report]
# exclude_lines = ['if TYPE_CHECKING:', 'if __name__ == .__main__.:', 'no cov']
